{% set name = "insarscript" %}
{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #url: https://github.com/jldz9/InSARScript/archive/refs/tags/v{{ version }}.tar.gz
  #sha256: 279cf5786dee9492a5a2be54b5c597f68672039bd676cecc02160410b1e85661

build:
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - gdal >=3.8
    - sqlite >=3.44
    - proj >=9.4
    - mintpy 
    - asf_search 
    - colorama 
    - contextily 
    - dem_stitcher 
    - hyp3_sdk 
    - python-box 
    - rasterio =1.4.3
    - sentineleof 
    - tomli-w 
    - numpy <2.0

test: 
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - insarscript
  commands:
    - pip check

about:
  home: https://github.com/jldz9/InSARScript
  license: MIT
  license_file: LICENSE
  summary: "Hassle-free InSAR processing scripts for multiple satellites"
  doc_url: https://jldz9.github.io/InSARScript/


extra:
  recipe-maintainers:
    - jldz9
