name: insarhub
channels:
    - defaults
    - conda-forge
dependencies:
    - python >=3.11,<3.13
    - gdal >=3.8
    - mintpy
    - pip
    - pip:
        - rasterio
        - asf_search
        - colorama
        - hyp3_sdk
        - dem_stitcher
        - contextily
        - sentineleof
        - cdsapi
        - fastapi
        - uvicorn
        - openpyxl
        - python-multipart
        - numpy <2.0
        