package:
  name: insarscript
  version: "0.0.1"

source:
  path: ./


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=61.0
    - wheel
    - git
  run:
    - python >=3.11
    - gdal>=3.8
    - sqlite>=3.44
    - isce2=2.6.4
    - mintpy=1.6.2
    - asf_search=10.0.4
    - colorama=0.4.6
    - contextily=1.6.2
    - dem_stitcher=2.5.12
    - hyp3_sdk=7.7.3
    - python-box=7.3.2
    - rasterio=1.4.3
    - sentineleof=0.11.1
    - tomli-w=1.2.0

   

  test: 
    imports:
      - insarscript

about:
  home: https://jldz9.github.io/InSARScript
  license: MIT
  license_file: LICENSE
  summary: "Hassle-free InSAR processing scripts for multiple satellites"