{% set name = "insarscript" %}
{% set version = "0.0.1" %}
{% set python_min = "3.11" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jldz9/InSARScript/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4a7e15b7b7d279620811dd10c6a1ea2d74ca8f4cf443173dfe3ac7468a4444b3

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >={{ python_min }}
    - gdal >=3.8
    - sqlite >=3.44
    - proj >=9.4
    - mintpy 
    - asf_search 
    - colorama 
    - contextily 
    - dem_stitcher 
    - hyp3_sdk 
    - python-box 
    - rasterio =1.4.3
    - sentineleof 
    - tomli-w 

test: 
  requires:
    - python {{ python_min }}
  imports:
    - insarscript

about:
  home: https://github.com/jldz9/InSARScript
  license: MIT
  license_file: LICENSE
  summary: "Hassle-free InSAR processing scripts for multiple satellites"
  doc_url: https://jldz9.github.io/InSARScript/


extra:
  recipe-maintainers:
    - jldz9
